name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request with Changelog
        if: steps.semantic-release.outputs.new_release_published == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): v${{ steps.semantic-release.outputs.new_release_version }} [skip ci]"
          title: "chore(release): v${{ steps.semantic-release.outputs.new_release_version }}"
          body: "This PR updates the CHANGELOG.md for the new version. Merge this to finalize the versioning."
          branch: "release-v${{ steps.semantic-release.outputs.new_release_version }}"

      - name: Package Artifact
        if: steps.semantic-release.outputs.new_release_published == 'true'
        run: |
          NEW_TAG="v${{ steps.semantic-release.outputs.new_release_version }}"
          mkdir -p dist
          cp main.py README.md requirements.txt dist/
          cp -r collectors output utils dist/
          ZIP_NAME="aws-resource-inventory-${NEW_TAG}.zip"
          cd dist && zip -r ../$ZIP_NAME .
          echo "ZIP_PATH=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload to GitHub Release
        if: steps.semantic-release.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.semantic-release.outputs.new_release_version }}"
          files: ${{ env.ZIP_PATH }}
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}